# Form implementation generated from reading ui file 'd:\pyqt6\.venv\Calci.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QTimer

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 651)
        MainWindow.setMinimumSize(QtCore.QSize(484, 651))
        MainWindow.setMaximumSize(QtCore.QSize(484, 651))
        MainWindow.setStyleSheet("QMianWindow{\n"
"background-color: rgb(75, 150, 123);\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.push_del = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.push_del.setFont(font)
        self.push_del.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_del.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_del.setObjectName("push_del")
        self.gridLayout.addWidget(self.push_del, 1, 2, 1, 1)
        self.push_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_clear.sizePolicy().hasHeightForWidth())
        self.push_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.push_clear.setFont(font)
        self.push_clear.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_clear.setAutoFillBackground(False)
        self.push_clear.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_clear.setFlat(False)
        self.push_clear.setObjectName("push_clear")
        self.gridLayout.addWidget(self.push_clear, 1, 0, 1, 2)
        self.push_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_minus.sizePolicy().hasHeightForWidth())
        self.push_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.push_minus.setFont(font)
        self.push_minus.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_minus.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_minus.setObjectName("push_minus")
        self.gridLayout.addWidget(self.push_minus, 2, 3, 1, 1)
        self.push_four = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_four.sizePolicy().hasHeightForWidth())
        self.push_four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_four.setFont(font)
        self.push_four.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_four.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_four.setObjectName("push_four")
        self.gridLayout.addWidget(self.push_four, 3, 0, 1, 1)
        self.push_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_plus.sizePolicy().hasHeightForWidth())
        self.push_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.push_plus.setFont(font)
        self.push_plus.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_plus.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_plus.setObjectName("push_plus")
        self.gridLayout.addWidget(self.push_plus, 1, 3, 1, 1)
        self.push_three = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_three.sizePolicy().hasHeightForWidth())
        self.push_three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.push_three.setFont(font)
        self.push_three.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_three.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_three.setObjectName("push_three")
        self.gridLayout.addWidget(self.push_three, 2, 2, 1, 1)
        self.push_one = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_one.sizePolicy().hasHeightForWidth())
        self.push_one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_one.setFont(font)
        self.push_one.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_one.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_one.setObjectName("push_one")
        self.gridLayout.addWidget(self.push_one, 2, 0, 1, 1)
        self.push_six = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_six.sizePolicy().hasHeightForWidth())
        self.push_six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_six.setFont(font)
        self.push_six.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_six.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_six.setObjectName("push_six")
        self.gridLayout.addWidget(self.push_six, 3, 2, 1, 1)
        self.push_div = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_div.sizePolicy().hasHeightForWidth())
        self.push_div.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.push_div.setFont(font)
        self.push_div.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_div.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_div.setObjectName("push_div")
        self.gridLayout.addWidget(self.push_div, 3, 3, 1, 1)
        self.push_zero = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_zero.sizePolicy().hasHeightForWidth())
        self.push_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_zero.setFont(font)
        self.push_zero.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_zero.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_zero.setObjectName("push_zero")
        self.gridLayout.addWidget(self.push_zero, 5, 0, 1, 2)
        self.push_five = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_five.sizePolicy().hasHeightForWidth())
        self.push_five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_five.setFont(font)
        self.push_five.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_five.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_five.setObjectName("push_five")
        self.gridLayout.addWidget(self.push_five, 3, 1, 1, 1)
        self.push_equal = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_equal.sizePolicy().hasHeightForWidth())
        self.push_equal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.push_equal.setFont(font)
        self.push_equal.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_equal.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_equal.setObjectName("push_equal")
        self.gridLayout.addWidget(self.push_equal, 5, 3, 1, 1)
        self.push_dot = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_dot.sizePolicy().hasHeightForWidth())
        self.push_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.push_dot.setFont(font)
        self.push_dot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_dot.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_dot.setObjectName("push_dot")
        self.gridLayout.addWidget(self.push_dot, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(41)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.push_two = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_two.sizePolicy().hasHeightForWidth())
        self.push_two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_two.setFont(font)
        self.push_two.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_two.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_two.setObjectName("push_two")
        self.gridLayout.addWidget(self.push_two, 2, 1, 1, 1)
        self.push_mult = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_mult.sizePolicy().hasHeightForWidth())
        self.push_mult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.push_mult.setFont(font)
        self.push_mult.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_mult.setMouseTracking(False)
        self.push_mult.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(245, 158, 66);\n"
"}")
        self.push_mult.setObjectName("push_mult")
        self.gridLayout.addWidget(self.push_mult, 4, 3, 1, 1)
        self.push_nine = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_nine.sizePolicy().hasHeightForWidth())
        self.push_nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_nine.setFont(font)
        self.push_nine.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_nine.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_nine.setObjectName("push_nine")
        self.gridLayout.addWidget(self.push_nine, 4, 2, 1, 1)
        self.push_eight = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_eight.sizePolicy().hasHeightForWidth())
        self.push_eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_eight.setFont(font)
        self.push_eight.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_eight.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_eight.setObjectName("push_eight")
        self.gridLayout.addWidget(self.push_eight, 4, 1, 1, 1)
        self.push_seven = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_seven.sizePolicy().hasHeightForWidth())
        self.push_seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.push_seven.setFont(font)
        self.push_seven.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_seven.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"background-color:rgb(191,191,191);\n"
"border-radius:25px;\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"color:rgb(61,61,61);\n"
"\n"
"}\n"
"QPushButton:Hover{\n"
"background-color:rgb(254,0,0);\n"
"}")
        self.push_seven.setObjectName("push_seven")
        self.gridLayout.addWidget(self.push_seven, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.push_one.clicked.connect(self.method_1)
        self.push_two.clicked.connect(self.method_2)
        self.push_three.clicked.connect(self.method_3)
        self.push_four.clicked.connect(self.method_4)
        self.push_five.clicked.connect(self.method_5)
        self.push_six.clicked.connect(self.method_6)
        self.push_seven.clicked.connect(self.method_7)
        self.push_eight.clicked.connect(self.method_8)
        self.push_nine.clicked.connect(self.method_9)
        self.push_zero.clicked.connect(self.method_0)
        
        self.push_clear.clicked.connect(self.method_clear)
        self.push_del.clicked.connect(self.method_del)
        
        self.push_plus.clicked.connect(self.method_plus)
        self.push_minus.clicked.connect(self.method_minus)
        self.push_div.clicked.connect(self.method_div)
        self.push_mult.clicked.connect(self.method_mult)
        self.push_dot.clicked.connect(self.method_dot)
        self.push_equal.clicked.connect(self.method_equal)
        
        self.timer = QTimer()
        self.timer.setSingleShot(True)
        self.timer.setInterval(3000)
        self.timer.timeout.connect(self.timer_finished)
        
        
    def timer_finished(self):
        self.label.setText("")
        
    def method_1(self):
        text=self.label.text()
        self.label.setText(text+"1")
    
    def method_2(self):
         text=self.label.text()
         self.label.setText(text+"2")
    
    def method_3(self):
        text=self.label.text()
        self.label.setText(text+"3")
    
    def method_4(self):
        text=self.label.text()
        self.label.setText(text+"4")
     
    def method_5(self):
        text=self.label.text()
        self.label.setText(text+"5")
       
    def method_6(self):
        text=self.label.text()
        self.label.setText(text+"6")
      
    def method_7(self):
        text=self.label.text()
        self.label.setText(text+"7")
       
    def method_8(self):
        text=self.label.text()
        self.label.setText(text+"8")
      

    def method_9(self):
        text=self.label.text()
        self.label.setText(text+"9")
       
    def method_0(self):
        text=self.label.text()
        self.label.setText(text+"0")
       
    def method_clear(self):
        self.label.setText(" ")
       
    def method_del(self):
        text=self.label.text()
        self.label.setText(text[:len(text)-1])
          
    def method_plus(self):
        text=self.label.text()
        self.label.setText(text+"+")
      
    def method_minus(self):
        text=self.label.text()
        self.label.setText(text+"-")
       
    def method_div(self):
        text=self.label.text()
        self.label.setText(text+"/")
       
    def method_mult(self):
        text=self.label.text()
        self.label.setText(text+"*")
       
    def method_dot(self):
        text=self.label.text()
        self.label.setText(text+".")
       
    def method_equal(self):
        text=self.label.text()
        self.label.setText(text+"=")
        try:
            ans = eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")
            self.timer.start()
            
            
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.push_del.setText(_translate("MainWindow", "Del"))
        self.push_del.setShortcut(_translate("MainWindow", "Del"))
        self.push_clear.setText(_translate("MainWindow", "Clear"))
        self.push_clear.setShortcut(_translate("MainWindow", "Backspace"))
        self.push_minus.setText(_translate("MainWindow", "-"))
        self.push_minus.setShortcut(_translate("MainWindow", "-"))
        self.push_four.setText(_translate("MainWindow", "4"))
        self.push_four.setShortcut(_translate("MainWindow", "4"))
        self.push_plus.setText(_translate("MainWindow", "+"))
        self.push_plus.setShortcut(_translate("MainWindow", "+"))
        self.push_three.setText(_translate("MainWindow", "3"))
        self.push_three.setShortcut(_translate("MainWindow", "3"))
        self.push_one.setText(_translate("MainWindow", "1"))
        self.push_one.setShortcut(_translate("MainWindow", "1"))
        self.push_six.setText(_translate("MainWindow", "6"))
        self.push_six.setShortcut(_translate("MainWindow", "6"))
        self.push_div.setText(_translate("MainWindow", "÷"))
        self.push_div.setShortcut(_translate("MainWindow", "/"))
        self.push_zero.setText(_translate("MainWindow", "0"))
        self.push_zero.setShortcut(_translate("MainWindow", "0"))
        self.push_five.setText(_translate("MainWindow", "5"))
        self.push_five.setShortcut(_translate("MainWindow", "5"))
        self.push_equal.setText(_translate("MainWindow", "="))
        self.push_equal.setShortcut(_translate("MainWindow", "Enter"))
        self.push_dot.setText(_translate("MainWindow", "."))
        self.push_dot.setShortcut(_translate("MainWindow", "."))
        self.push_two.setText(_translate("MainWindow", "2"))
        self.push_two.setShortcut(_translate("MainWindow", "2"))
        self.push_mult.setText(_translate("MainWindow", "x"))
        self.push_mult.setShortcut(_translate("MainWindow", "*"))
        self.push_nine.setText(_translate("MainWindow", "9"))
        self.push_nine.setShortcut(_translate("MainWindow", "9"))
        self.push_eight.setText(_translate("MainWindow", "8"))
        self.push_eight.setShortcut(_translate("MainWindow", "8"))
        self.push_seven.setText(_translate("MainWindow", "7"))
        self.push_seven.setShortcut(_translate("MainWindow", "7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui =Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())